version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.54.0
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    environment:
#      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: "true"
