name: Main

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: "The branch, tag or SHA to checkout. See actions/checkout 'ref'."
        required: false
        type: string

  push:
    branches: [ main ]


concurrency:
  group: "Releases: ${{ github.workflow }} @ ${{ inputs.checkout-ref }} ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true


permissions:
  contents: write


jobs:

  tests:
    uses: ./.github/workflows/run_tests.yml
    permissions:
      checks: write
      contents: read
    with:
      checkout-ref: ${{ inputs.checkout-ref }}
